apiVersion: v1
kind: Service
metadata:
  name: mandi-service
  namespace: mandi
spec:
  type: LoadBalancer
  selector:
    app: mandi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
